version: '3.3'
services:

  db_projects_service:
    image: postgres
    networks:
      - projects_network
    restart:
      always
    ports:
      - "5432:5432"

  projects_service:
    build: ./project_service
    depends_on:
      - db_projects_service
    networks:
      - projects_network
    restart:
      always
    ports:
      - "5000:5000"



networks:
  projects_network:
#  etl_network:
#  auth_network:
