version: '3.3'
services:

  calculation_service:
    build: ./calculation_service
    container_name: calculation_service
    restart: always
    ports:
      - "5000:6050"
    depends_on:
      - projects_service


  contracts_service:
    build: ./contracts_service
    container_name: contracts_service
    restart: always
    ports:
     - "5000:7000"
    

  etl_service:
    build: ./etl_service
    container_name: etl_service
    restart: always
    depends_on:
      - projects_service
    ports:
      - "5000:5050"

  projects_service:

    build: ./project_service
    container_name: projects_service
    depends_on:
      - db_projects_service
    networks:
      - projects_network
    restart:
      always
    ports:
      - "5000:5000"

  users_service:
    build: ./users_service
    container_name: users_service
    restart: always
    ports:
     - "5000:7050"



  db_projects_service:
    image: postgres
    networks:
      - projects_network
    restart:
      always

networks:
    projects_network:
    etl_network:
