version: '3.3'
services:

#  authentication_service:
#    build: ./authentication_service
#    container_name: authentication_service
#    restart: always
#    ports:
#      - "5000:6000"

#  calculation_service:
#    build: ./calculation_service
#    container_name: calculation_service
#    restart: always
#    ports:
#      - "5000:6050"
#    depends_on:
#      - projects_service


#  contracts_service:
#    build: ./contracts_service
#    container_name: contracts_service
#    restart: always
#    ports:
#     - "5000:7000"

  etl_service:
    build: ./etl_service
    container_name: etl_service
    restart: always
    ports:
      - "5050:5050"

  projects_service:
    build: ./project_service
    restart:
      always
    ports:
      - "5000:5000"

#  users_service:
#    build: ./users_service
#    container_name: users_service
#    restart: always
#    ports:
#     - "5000:7050"

  db_projects_service:
    image: postgres
    restart:
      always

  db_user_service:
    image: postgres
    restart:
      always

  db_contracts_service:
    image: postgres
    restart:
      always

